Get http://localhost:3000


### protected route
Get http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzU2NTg4NDEsImV4cCI6MTY3NTY2MjQ0MX0.kljGSg8f5M5VlzHGs3of_MQ3lbrWDqBRpuYWlRpk-Oao8cBf9qjA5HAwSqe_lzt6rVTULyIOGa28IslAoXpjmjAMnPtzZFEnF9b4ocPIitM4oGv9nDRNSJPzSjMj011xzA_DcA6mxFfEmKLrKs5jafcH2BQNklc8eYsXJM-3GtYkCR1bywSebrq4MDNrrFuOk30rpnPvKkrbw00BcMMaL_UxQIjWZjtmyyDzlaw6H3fKR29CRyr4Ni6RdB4vXfn_if-SYuH2KyLHrYMWCqLsZMaWnGV45tes2MYNlpb7XzNgS5AcSSWw7Uvmx0NKTd_PVUWFuHrjUEd3aHM0OJTKUv7daaYSjrijlHUv0DBZyhm0u5bvePZWPY6IXIZl3gYFf5fhhcpqH_M8ZD-4i-4AO3M28PS3oP_Mzr4AOVTSv9ErhvuVUEITEFYnypzrQcIl-n8yAUqcHjdz-09Ze7xfFbqHLPYneDJcACjbeurCJB9bdkLU9xeLdR6XBGB8aeMg

